# Generated by Django 3.1.2 on 2020-10-10 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Auction_title', models.CharField(max_length=64)),
                ('Auction_description', models.TextField(max_length=200)),
                ('Auction_photo', models.ImageField(upload_to='AuctionPhotos')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_content', models.TextField(max_length=200)),
                ('Comment_datetime', models.DateTimeField(auto_now=True)),
                ('Comment_Auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommentAuction_id', to='auctions.auction')),
                ('Comment_User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CommentUser_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bid_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Bid_Auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BidAuction_id', to='auctions.auction')),
                ('Bid_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BidUser_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='Auction_Categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Category_id', to='auctions.category'),
        ),
    ]
