# Generated by Django 3.1.2 on 2020-10-12 13:22

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201012_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='Auction_photo',
            field=django_resized.forms.ResizedImageField(crop=None, default='AuctionPhotos/？？？.jpg', force_format=None, keep_meta=True, quality=100, size=[200, 200], upload_to='AuctionPhotos'),
        ),
    ]
