# Generated by Django 3.1.2 on 2020-10-19 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20201019_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='Auction_Category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AuctionCategory_id', to='auctions.category'),
        ),
    ]
