# Generated by Django 3.1.2 on 2020-10-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201011_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category_title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
