# Generated by Django 3.1.2 on 2020-10-11 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201011_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='Auction_User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AuctionUser_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='Auction_Categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AuctionCategory_id', to='auctions.category'),
        ),
    ]
