# Generated by Django 3.1.2 on 2020-10-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201012_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='Auction_photo',
            field=models.ImageField(default='AuctionPhotos/???.jpg', upload_to='AuctionPhotos'),
        ),
    ]
