# Generated by Django 3.1.2 on 2020-10-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201019_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='Auction_startingbid',
            field=models.IntegerField(default=0),
        ),
    ]
