# Generated by Django 3.1.2 on 2020-10-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auction_auction_startingbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_watchlist',
            field=models.ManyToManyField(to='auctions.Auction'),
        ),
    ]
